const mongoose = require("mongoose");

const RenewalDataSchema = new mongoose.Schema({
  Chesskid_Gold: { type: Boolean, default: false },
  Added_Time: { type: Date },
  Added_User: { type: String },
  CGST: { type: Number, default: 0 },
  Cancelled_Invoice: { type: Boolean, default: false },
  Expiry_Date: { type: String }, // stored as string (e.g. "12-08-2022")
  Pretax_Amount: { type: Number },
  ID: { type: String },
  Invoice_No: { type: String },
  Invoice_seriel_number: { type: String },
  Kid_ID: { type: String },
  Kid_Name_prefix: { type: String },
  Kid_Name_first_name: { type: String },
  Kid_Name_last_name: { type: String },
  Kid_Name_suffix: { type: String },
  Last_Interacted_with: { type: String },
  Last_interacted_with_user_prof: { type: String },
  Mode_of_Payment: { type: String },
  Modified_Time: { type: Date },
  Modified_User: { type: String },
  Number_of_Classes: { type: Number },
  Weekly_4_to_6_classes: { type: String },
  Weekly_2_classes: { type: String },
  Paid_Date: { type: String },
  Parent_Email: { type: String },
  Parent_Name_prefix: { type: String },
  Parent_Name_first_name: { type: String },
  Parent_Name_last_name: { type: String },
  Parent_Name_suffix: { type: String },
  Payment_Confirmed: { type: Boolean },
  Payment_Count: { type: Number },
  Payment_ID: { type: String },
  Payment_Mode: { type: String },
  Payment_Success: { type: Boolean },
  Payment_confirmed_by: { type: String },
  Classes_before_8am_and_after_7pm_IST: { type: Boolean },
  Please_choose_the_type_of_Plan: { type: String },
  Previous_Active_Profile: { type: Boolean },
  Previous_Class_Expiration_Date: { type: String },
  Previous_Date_of_Joining: { type: String },
  Previous_Last_Renewed_Date: { type: String },
  Previous_Paused_Profile: { type: Boolean },
  Previous_Presales: { type: Boolean },
  Previously_Classes_after_last_renewal: { type: Number },
  Previously_Renewed_Amount: { type: Number },
  Reason_for_Cancellation: { type: String },
  Record_Status: { type: Number },
  Renewal_Type: { type: String },
  Renewal_Type_Number: { type: Number },
  SGST: { type: Number },
  Tax: { type: Number },
  Total_Amount: { type: Number },
  Voucher_Amount: { type: Number },
  Weekend_Classes: { type: Boolean }
});

module.exports = mongoose.model("RenewalDataKims", RenewalDataSchema);
